[package]
name = "smbdump"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
chrono = "0.4.38"
num-derive = "0.4.2"
num-traits = "0.2.19"
strum = "0.26.3"
strum_macros = "0.26.4"

[features]
default = ["color"]
color = []
